### ISSUE TITLE
创建链接失败，前端无提示

### ISSUE THREAD

**Issue by liuxingar** [tengfei-xy/siyuan-plugin-share-system-engine#10]
![image](https://github.com/user-attachments/assets/7e20913f-4585-4b3a-92d5-ba5ac31fcc09)

**Comment by liuxingar** [comment]
里面的域名替换了一下，其他日志信息没做任何增删
[spss_engine.zip](https://github.com/user-attachments/files/17336060/spss_engine.zip)

**Comment by tengfei-xy** [comment]
好的，那应该是前端发送的数据（或生成数据失败）到应用时，由于网络错误，发送失败。前端请求有请求失败的日志嘛？下个版本，我打算吧web服务器和应用和数据库整合到一个应用中，这样出错的概率比较低，当前的架构有点复杂了。

**Comment by tengfei-xy** [comment]
这个问题脱了好久，您有向日葵或者todesk嘛？方便我远程过来看看嘛？理论上说，只要网络通，应用肯定有日志输出

**Comment by liuxingar** [comment]
![image](https://github.com/user-attachments/assets/c7a7648a-a651-4da0-87cb-10cf6bdd0919)

**Comment by tengfei-xy** [comment]
上传文件过大导致，默认nginx限制了100MB。
