### ISSUE TITLE
分享链接在H5端会出现目录遮挡内容的情况，可否优化？

### ISSUE THREAD

**Issue by Dotaallstars** [tengfei-xy/siyuan-plugin-share-system-engine#13]
H5端查看的时候，目录默认在左侧居中，会遮挡文章内容，可否进一步优化为默认折叠或者在右下角？
![image](https://github.com/user-attachments/assets/43484550-5eea-4828-af66-0f904f7e0cfc)

**Comment by tengfei-xy** [comment]
已更新，如果使用自建服务器，请更新最新版2.2.3。如果使用默认的分享服务器，请重新分享。

**Comment by Dotaallstars** [comment]
> 已更新，如果使用自建服务器，请更新最新版2.2.3。如果使用默认的分享服务器，请重新分享。

已更新，如果可以进一步优化为折叠后完全无文字就更好了，目前折叠后会有最右侧一个字：
![image](https://github.com/user-attachments/assets/15155d86-d2b0-4917-8fbc-0f1a3df7fe82)

![image](https://github.com/user-attachments/assets/d60b5a7e-f53d-42a1-acc1-1b8c5e1ba5ae)

**Comment by Dotaallstars** [comment]
此外，更新后，无论是否显示左侧目录，会出现标题提前换行的情况：
![image](https://github.com/user-attachments/assets/0b7405bd-479a-4e87-824b-7c870cc8a1e4)

**Comment by tengfei-xy** [comment]
> 文章标题前会出现一个小横条：

已处理。

**Comment by tengfei-xy** [comment]
换行和小横条似乎是某个思源笔记的某个插件的

**Comment by tengfei-xy** [comment]
暂时关闭，有需要再重新提issue
