### ISSUE TITLE
一直出现unknown certificates，只改了链接

### ISSUE THREAD

**Issue by Mowen-M** [tengfei-xy/siyuan-plugin-share-system-engine#14]
![image](https://github.com/user-attachments/assets/dfa7f278-8113-4b1c-b8be-a8e291e775d0)

**Comment by Mowen-M** [comment]
![image](https://github.com/user-attachments/assets/2fb8db3e-38e5-4ea9-bea3-d45f319105e5)
是我插件这里设置有问题吗

**Comment by Mowen-M** [comment]
![image](https://github.com/user-attachments/assets/78cd0e35-524c-4b7c-bd0d-d969d0d29809)
后台地址应该填share link对吧
它那个监听地址就是容器内部的我应该没理解错

**Comment by tengfei-xy** [comment]
1. 变量里的SPSS_WEB_SLL_CERT的/pem和/key应该是文件路径，表示根目录的pem文件和key文件，但你nas上的存储空间设置，这俩个却是文件夹。
2. 监听地址方面应该没有错，不然日志里也不会有通信方面的ssl错误。

**Comment by Mowen-M** [comment]
解决了，我也不知道原因，很奇怪
