### ISSUE TITLE
是否可以提供NAS部署方案

### ISSUE THREAD

**Issue by liuxingar** [tengfei-xy/siyuan-plugin-share-system-engine#2]
是否可以提供NAS部署方案，根据当前部署说明，在NAS上没有部署成功

**Comment by tengfei-xy** [comment]
是用docket方式 部署嘛？nas上支持docker和docker-compose嘛？请发一下错误日志。

**Comment by liuxingar** [comment]
感谢回复！
1、报错日志：
docker-compose仅修改两处，见下图红框：
docker-compose 任何参数不改，报以下错误： 
shangzhw
***@***.***
---- 回复的原邮件 ----
***@***.***>发送日期2024年6月30日 ***@***.***>***@***.***>,
***@***.***>主题Re: [tengfei-xy/siyuan-plugin-share-system-engine] 是否可以提供NAS部署方案 (Issue #2)
是用docket方式 部署嘛？nas上支持docker和docker-compose嘛？请发一下错误日志。

**Comment by tengfei-xy** [comment]
这个容器平台是什么？我可以进入测试下嘛？

**Comment by liuxingar** [comment]
群晖NAS，我如何联系你提供远程方式？

**Comment by liuxingar** [comment]
> 这个容器平台是什么？我可以进入测试下嘛？

群晖NAS，我如何联系你提供远程方式？

**Comment by tengfei-xy** [comment]
微信：uBpHJlVdn5k15G3dhLh1

**Comment by tengfei-xy** [comment]
目前不支持单文件的docker-compose.yml的部署方式，需要通过[下载](https://github.com/tengfei-xy/siyuan-plugin-share-system-engine/releases/tag/v1.3.2)指定包来构建
