### ISSUE TITLE
建议 使用 静态html资源,省去 mysql

### ISSUE THREAD

**Issue by 4698to** [tengfei-xy/siyuan-plugin-share-system-engine#3]
既然导出是html ，直接使用文件名访问这样的静态部署不是更省事吗，还能避免使用 mysql ，部署起来更方便

**Comment by tengfei-xy** [comment]
假设有用户甲分享了名称为A的文章，用户乙分享了名称同样为A的文章，文件名应该如何定义呢？web服务器的如何存储这二者用户的静态资源（.html、.css、.jpg等）

**Comment by SelfEnough** [comment]
> 假设有用户甲分享了名称为A的文章，用户乙分享了名称同样为A的文章，文件名应该如何定义呢？web服务器的如何存储这二者用户的静态资源（.html、.css、.jpg等）？
名称+时间戳？或者直接时间戳命名html？？
顺便，大佬能否考虑 让HTML支持侧边大纲展示？
这样规范的MD阅读起来更方便

**Comment by tengfei-xy** [comment]
数据库的意义在于可以单独管理每个网页和统计其信息。比如网页过期时间，网页访问秘钥（虽然这个没有实现），页面访问次数。不过是需求不同罢了。

**Comment by tengfei-xy** [comment]
此问题过去太久，关闭了。最新版v2.0版本仅一个程序就可以运行，不需要mysql依赖。
