### ISSUE TITLE
docker部署方式可否只部署spss_engine

### ISSUE THREAD

**Issue by shellingford37** [tengfei-xy/siyuan-plugin-share-system-engine#4]
docker部署方式可否只部署spss_engine？ 把mysql相关参数配置化，这样在已有mysql、nginx的服务器上可以少部署2个容器。
主要是一般很少为一个应用单独部署一个mysql实例，通常都是分个它一个库

**Comment by tengfei-xy** [comment]
需要改下代码，过几天发布～

**Comment by shellingford37** [comment]
我拿源码构建了一个单独的docker镜像，启动的时候会加载config.yaml  ,  然后配了自己的mysql，数据库名、数据库用户名、密码都可以配置。
所以感觉docker映射外部的config.yaml就行

**Comment by tengfei-xy** [comment]
是的，这样也行

**Comment by tengfei-xy** [comment]
框架已更新，支持仅仅部署spss_engine
