### ISSUE TITLE
大佬能否考虑 让HTML支持侧边大纲展示？

### ISSUE THREAD

**Issue by SelfEnough** [tengfei-xy/siyuan-plugin-share-system-engine#5]
这样MD阅读起来更方便美观些

**Comment by tengfei-xy** [comment]
想法不错，有可执行的方法不？

**Comment by SelfEnough** [comment]
没有。。。。。

**Comment by tengfei-xy** [comment]
有个大概的思路是，根据生成的html，获取各级标题的元素，然后生成对应到html的a标签并放到一起。

**Comment by tengfei-xy** [comment]
最近状态不好，懒得写哈哈哈哈哈哈

**Comment by SelfEnough** [comment]
或者不知道有没有那种OTC的JS插件， 在HTML加载的时候嵌入，自动抽目录显示

**Comment by tengfei-xy** [comment]
这也是个路子

**Comment by SelfEnough** [comment]
还真找到了几个
https://github.com/Colin9R/syllabus
https://github.com/ynjynjynj119/typora-menu
https://github.com/suliyea/typora-2-html

**Comment by tengfei-xy** [comment]
有空我搞下

**Comment by tengfei-xy** [comment]
v2.1.0版本已支持此功能！
