### ISSUE TITLE
docker自建，生成链接失败，提示缺表

### ISSUE THREAD

**Issue by liuxingar** [tengfei-xy/siyuan-plugin-share-system-engine#7]
插件提示成功，但是未生成链接，后台报错缺表
![1](https://github.com/user-attachments/assets/0f40af83-c061-4a47-a1bf-f863a060978a)
![2](https://github.com/user-attachments/assets/cc07739d-9485-4db8-bd27-d0e423a3693c)

**Comment by liuxingar** [comment]
而且很奇怪的是，docker-compose.yml中镜像版本号我改了，提示信息中还是1.3.0
![image](https://github.com/user-attachments/assets/c3461294-e862-4bb5-81ae-639ae337336c)

**Comment by tengfei-xy** [comment]
1. 缺少表的话，需要执行[init.sh](https://github.com/tengfei-xy/siyuan-plugin-share-system-engine/blob/main/docker/init.sh)(自动的方式)，或者将[ddl.sql](https://github.com/tengfei-xy/siyuan-plugin-share-system-engine/blob/main/docker/mysql/ddl.sql)（手动的方式）。
2. 应用的日志中提示插件版本1.3.0，是思源笔记上的插件的版本，并非应用本身的版本。应用本身的版本在程序启动时提示。

**Comment by tengfei-xy** [comment]
问题过去太久，请尝试最新版。最新版支持自动建表
