### ISSUE TITLE
是否可以点击插件图标直接进入配置页面，而不是显示一个配置按钮再点击进去

### ISSUE THREAD

**Issue by liuxingar** [tengfei-xy/siyuan-plugin-share-system-engine#8]
![image](https://github.com/user-attachments/assets/f89c4551-05ed-4e3f-b0ab-00e3304c74aa)

**Comment by tengfei-xy** [comment]
下个版本我更新下

**Comment by tengfei-xy** [comment]
已解决，插件请更新到最新版v2.0.0
